# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oprc-object.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11oprc-object.proto\x12\x04oprc\"\x9c\x02\n\x0cProtoOObject\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x08revision\x18\x02 \x01(\x03\x12\x10\n\x03\x63ls\x18\x03 \x01(\tH\x01\x88\x01\x01\x12!\n\x05state\x18\x04 \x01(\x0b\x32\r.oprc.OOStateH\x02\x88\x01\x01\x12*\n\x04refs\x18\x05 \x03(\x0b\x32\x1c.oprc.ProtoOObject.RefsEntry\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\x12\x12\n\nlastOffset\x18\x07 \x01(\x03\x12\x14\n\x07lastInv\x18\x08 \x01(\tH\x03\x88\x01\x01\x1a+\n\tRefsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x05\n\x03_idB\x06\n\x04_clsB\x08\n\x06_stateB\n\n\x08_lastInv\"=\n\rProtoPOObject\x12\x1e\n\x04meta\x18\x01 \x01(\x0b\x32\x10.oprc.ProtoOMeta\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\xff\x01\n\nProtoOMeta\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08revision\x18\x02 \x01(\x03\x12\x0b\n\x03\x63ls\x18\x03 \x01(\t\x12,\n\x06verIds\x18\x04 \x03(\x0b\x32\x1c.oprc.ProtoOMeta.VerIdsEntry\x12(\n\x04refs\x18\x05 \x03(\x0b\x32\x1a.oprc.ProtoOMeta.RefsEntry\x12\x12\n\nlastOffset\x18\x06 \x01(\x03\x1a-\n\x0bVerIdsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a+\n\tRefsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xcf\x01\n\x07OOState\x12\x35\n\x0coverrideUrls\x18\x01 \x03(\x0b\x32\x1f.oprc.OOState.OverrideUrlsEntry\x12)\n\x06verIds\x18\x02 \x03(\x0b\x32\x19.oprc.OOState.VerIdsEntry\x1a\x33\n\x11OverrideUrlsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a-\n\x0bVerIdsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x1a\n\x16org.hpcclab.oaas.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oprc_object_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026org.hpcclab.oaas.protoP\001'
  _globals['_PROTOOOBJECT_REFSENTRY']._loaded_options = None
  _globals['_PROTOOOBJECT_REFSENTRY']._serialized_options = b'8\001'
  _globals['_PROTOOMETA_VERIDSENTRY']._loaded_options = None
  _globals['_PROTOOMETA_VERIDSENTRY']._serialized_options = b'8\001'
  _globals['_PROTOOMETA_REFSENTRY']._loaded_options = None
  _globals['_PROTOOMETA_REFSENTRY']._serialized_options = b'8\001'
  _globals['_OOSTATE_OVERRIDEURLSENTRY']._loaded_options = None
  _globals['_OOSTATE_OVERRIDEURLSENTRY']._serialized_options = b'8\001'
  _globals['_OOSTATE_VERIDSENTRY']._loaded_options = None
  _globals['_OOSTATE_VERIDSENTRY']._serialized_options = b'8\001'
  _globals['_PROTOOOBJECT']._serialized_start=28
  _globals['_PROTOOOBJECT']._serialized_end=312
  _globals['_PROTOOOBJECT_REFSENTRY']._serialized_start=232
  _globals['_PROTOOOBJECT_REFSENTRY']._serialized_end=275
  _globals['_PROTOPOOBJECT']._serialized_start=314
  _globals['_PROTOPOOBJECT']._serialized_end=375
  _globals['_PROTOOMETA']._serialized_start=378
  _globals['_PROTOOMETA']._serialized_end=633
  _globals['_PROTOOMETA_VERIDSENTRY']._serialized_start=543
  _globals['_PROTOOMETA_VERIDSENTRY']._serialized_end=588
  _globals['_PROTOOMETA_REFSENTRY']._serialized_start=232
  _globals['_PROTOOMETA_REFSENTRY']._serialized_end=275
  _globals['_OOSTATE']._serialized_start=636
  _globals['_OOSTATE']._serialized_end=843
  _globals['_OOSTATE_OVERRIDEURLSENTRY']._serialized_start=745
  _globals['_OOSTATE_OVERRIDEURLSENTRY']._serialized_end=796
  _globals['_OOSTATE_VERIDSENTRY']._serialized_start=543
  _globals['_OOSTATE_VERIDSENTRY']._serialized_end=588
# @@protoc_insertion_point(module_scope)
